name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    defaults:
      run:
        working-directory: test

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: build app x86
      shell: cmd
      run: ..\build.bat app x86
      working-directory: test

    - name: build app x64
      shell: cmd
      run: ..\build.bat app x64
      working-directory: test

    - name: build app ARM
      shell: cmd
      run: ..\build.bat app ARM
      working-directory: test

    - name: build app ARM64
      shell: cmd
      run: ..\build.bat app ARM64
      working-directory: test

    - name: build driver x86
      shell: cmd
      run: ..\build.bat driver x86
      working-directory: test

    - name: build driver x64
      shell: cmd
      run: ..\build.bat driver x64
      working-directory: test

    - name: build driver ARM
      shell: cmd
      run: ..\build.bat driver ARM
      working-directory: test

    - name: build driver ARM64
      shell: cmd
      run: ..\build.bat driver ARM64
      working-directory: test
